name: Release
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main


jobs:
  Spotify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Spotify
      run: ./build.sh
       
    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: Spotify Stable AppImage Builds
        automatic_release_tag: stable
        prerelease: false
        draft: false
        files: ./spotify/dist/Spotify-*-x86_64.AppImage*
        repo_token: ${{ secrets.GITHUB_TOKEN }}
